ALTER TABLE users
RENAME COLUMN name TO name_internal;

ALTER TABLE users
ADD COLUMN profile_visibility TEXT NOT NULL DEFAULT 'PRIVATE',
ADD COLUMN name_public TEXT,
ADD COLUMN image_url_internal TEXT,
ADD COLUMN image_url_public TEXT,
ADD COLUMN bio_internal TEXT,
ADD COLUMN bio_public TEXT;

--- Spring JDBC tries to update the user ID on save, which is not allowed with
--- GENERATED ALWAYS AS IDENTITY
ALTER TABLE users
ALTER COLUMN user_id SET GENERATED BY DEFAULT;
