CREATE TABLE projects (
  project_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  visibility TEXT NOT NULL,
  name TEXT NOT NULL,
  description_private TEXT,
  description_internal TEXT,
  description_public TEXT
);

CREATE TABLE project_authors (
  project_id INTEGER
    REFERENCES projects(project_id),
  author_id INTEGER
    REFERENCES users(user_id),
  PRIMARY KEY (project_id, author_id)
);
